# Generated by Django 3.2.19 on 2023-05-10 11:07

from django.db import migrations
from ...settings import env


def set_enable_account_confirmation_by_email_flag(apps, schema_editor):
    confirmation_flag = env.bool("ENABLE_ACCOUNT_CONFIRMATION_BY_EMAIL", True)
    SiteSettings = apps.get_model("site", "SiteSettings")
    SiteSettings.objects.update(enable_account_confirmation_by_email=confirmation_flag)


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0037_sitesettings_enable_account_confirmation_by_email"),
    ]

    operations = [
        migrations.RunPython(
            set_enable_account_confirmation_by_email_flag,
            migrations.RunPython.noop,
        ),
    ]
